forex/forex/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path
from .views import *


urlpatterns=[
    path('', IndexPage,  name='landing'),
    path('create', CreatePackagePage, name='create_package'),
    path('basic', Basic_Page, name='basic_package'),
    path('pro', Pro_Page, name='pro_package'),
    path('premium', Premium_Page, name='premium_package'),
    path('update/<slug:slug>/', UpdatePackagePage, name='update_package'),
    path('detail/<slug:slug>/', DetailPage, name='detail_package'),
    path('delete/<slug:slug>/', DeletePage, name='delete_package'),
    path('backoffice/', Dashboard, name='dashboard'),
    path('profile/', CustomerProfile, name='profile'),
    path('admin-dashboard/', Admin_Panel, name='admin'),
    path('delete/<str:pk>/', Delete_user, name='delete_user'),
    path('userpackage/<str:pk>/', UserPackage_Page, name='user_package'),
    path('signup/', SignupPage, name='signup'),
    path('login/', LoginPage, name='login'),
    path('logout/', Logout, name='logout'),
    path('checkout/<slug:slug>/', Add_to_cart, name='Add_to_cart'),
    path('remove/<slug:slug>/',Remove_from_cart , name='remove_from_cart'),
    path('cart/', CartFlow, name='cart'),
    path('checkout/', CheckoutSession, name='checkout'),
    path('invoice/<str:pk>', Instant_invoice, name='instant_invoice'),
    path('success/', Payment_complete, name='success'),


]

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User, null=True,blank=True, on_delete=models.CASCADE,unique=True)
    # username=models.CharField(max_length=200,null=True,blank=True,unique=True)
    first_name=models.CharField(max_length=20,null=True,blank=True)
    second_name=models.CharField(max_length=20,null=True,blank=True)
    email=models.EmailField(null=True,blank=True)
    image=models.ImageField(upload_to='picture/',null=True,blank=True)
    id_no=models.CharField(max_length=200,null=True,blank=True)
    date_joined=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)
    
    class Meta:
        ordering=['-date_joined']


class Package(models.Model):
    Category=(
        ('basic','basic'),
        ('pro','pro'),
        ('premium','premium'),
        ('feedback','feedback')
    )
    name=models.CharField(max_length=200,null=True,blank=True)
    price=models.FloatField(default=0)
    image=models.ImageField(blank=True,null=True)
    slug=models.SlugField(blank=True,null=True)
    category=models.CharField(max_length=100,blank=True,null=True,choices=Category)
    quantity=models.IntegerField(default=1)
    description=models.TextField()
    date_added=models.DateField(auto_now_add=True,null=True, blank=True)
    date_ordered=models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return self.name
    
    def product_price(self):
        return self.price
    
    class Meta:
        ordering=['-date_added']
    


class Cart(models.Model):
    customer=models.OneToOneField(Customer,null=True, blank=True, on_delete=models.CASCADE)
    package=models.ManyToManyField(Package,blank=True,)
    date_ordered=models.DateTimeField(null=True)


    def __str__(self):
        return str(self.customer)

    def total_sum(self):
        price_list=[]
        for product in self.package.all():
            price_list.append(product.price)
        return sum(price_list)



class Invoice(models.Model):

    customer=models.ForeignKey(Customer,null=True, blank=True, on_delete=models.SET_NULL)
    cart=models.ForeignKey(Cart,null=True, blank=True, on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    order_id=models.CharField(max_length=200,null=True,blank=True)
    address=models.CharField(max_length=200,null=True,blank=True)
    btc_value=models.FloatField(blank=True,null=True)
    satoshi_value=models.IntegerField(blank=True,null=True)
    usd_value=models.IntegerField(blank=True,null=True)
    received=models.IntegerField(blank=True,null=True)
    txid=models.CharField(max_length=300,null=True,blank=True)
    rbf=models.IntegerField(blank=True,null=True)
    date_created=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.cart}|{self.id}'
   

class UserPackage(models.Model):
    customer=models.OneToOneField(Customer,null=True, blank=True, on_delete=models.CASCADE)
    package=models.ManyToManyField(Package,blank=True,)

    def __str__(self):
        return str(self.id)

forex/frontend/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PackageForm(forms.ModelForm):
    class Meta:
        model= Package
        fields='__all__'
        exclude=['date_added','slug']

class RegistrationForm(UserCreationForm):
    first_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter First Name'}))
    last_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Last Name'}))
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Username'}))
    email=forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Enter email'}))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    class Meta:
        model=User
        fields= ['first_name','last_name','username','email','password1','password2']


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=['image']


class UserPackageForm(forms.ModelForm):
    class Meta:
        model=UserPackage
        fields='__all__'

frontend/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from .forms import *
from django.utils.text import slugify
from django.http import Http404,HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .decorators import authorised_user
from django.urls import reverse
from django.utils import timezone
import requests
from django.conf import settings
from .decorators import *
from django.core.mail import send_mail
from django.contrib.auth.views import redirect_to_login


from rest_framework import response
import json
import random
import uuid
import os


x=random.randint(10000,90000)

# Create your views here.
def IndexPage(request):
   
    dollar_amount=10000
    if dollar_amount >=10000:
        dollar_amount=+x
    btc_amount=dollar_amount/240000
    try:
        product=Package.objects.all()
        cart=Cart.objects.get(customer=request.user.customer)
        for product in cart.package.all():
            cart.package.remove(product)
        print("all items removed from cart.")
    except Exception as e:
        print(e)
    
    
    template='forex/index.html'
    context={
            'dollar_amount':dollar_amount,
            'btc_amount':btc_amount }

    return render(request,template,context)



def Basic_Page(request):
    packages=Package.objects.filter(category__iexact='basic')

    cart=''
    if request.user.is_authenticated:
        cart=Cart.objects.get(customer=request.user.customer)
        
        # for package in packages:
            
        #     if package not in cart.package.all():
        #         purchase=False

        #     elif cart.package.filter(id=package.id).exists():
        #         purchase=True

    template='forex/packages/basic.html'
    context={'packages':packages,
        'cart': cart
    #  'purchase':purchase, 
     }

    return render(request,template,context)

    
    
def Pro_Page(request):
    packages=Package.objects.filter(category__iexact='pro')

    cart=''
    if request.user.is_authenticated:
        cart=Cart.objects.get(customer=request.user.customer)


    template='forex/packages/pro.html'
    context={'packages':packages,'cart': cart}

    return render(request,template,context)

def Premium_Page(request):
    packages=Package.objects.filter(category__iexact='premium')


    cart=''
    if request.user.is_authenticated:
        cart=Cart.objects.get(customer=request.user.customer)
    

    template='forex/packages/premium.html'
    context={'packages':packages,'cart': cart }

    return render(request,template,context)


@authorised_user(roles=['admin','customer'])
def CreatePackagePage(request):

    form=PackageForm(request.POST or None,request.FILES)
    if request.method=='POST':
        if form.is_valid():
            q=form.save(commit=False)
            q.slug=slugify(q.name+'-'+q.description[:10])
            q.save()

        form=PackageForm()
    
    context={'form': form}
    template='forex/create.html'
    return render(request,template,context)




@authorised_user(roles=['admin'])
def UpdatePackagePage(request,slug):

    package=Package.objects.get(slug=slug)
    form=PackageForm(request.POST or None,request.FILES,instance=package)
    if request.method=='POST':
        if form.is_valid():
            q=form.save(commit=False)
            q.slug=slugify(q.name,+'-'+q.description[:10])
            q.save()

            
            form=PackageForm()
    
    context={'form': form}
    template='forex/update.html'
    return render(request,template,context)


    
@authorised_user(roles=['admin'])
def DetailPage(request,slug):
    
    
    package=Package.objects.get(slug=slug)
    purchase=False
    if request.user.is_authenticated:
        cart=Cart.objects.get(customer=request.user.customer)
        

        if package in cart.package.all():
            purchase=True
        
            
    template='forex/detail.html'
      
    context={'package':package,
    'purchase': purchase
    }
    return render(request,template,context)


@authorised_user(roles=['admin'])
def DeletePage(request,slug):
    package=Package.objects.get(slug=slug)
    package.delete()
    return render(request)


def SignupPage(request):
    form=RegistrationForm(request.POST or None,initial={'username':'' , 'password_1':'' })
    if request.method=='POST':
        if form.is_valid():
            user=form.save()
            first_name=form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            email=form.cleaned_data['email']
            # password=form.cleaned_data['password1']
            # confirm_password=form.cleaned_data['password2']
            # username=email.split('@')[0]

            # for n in range(10):
            number=random.randint(0000,900000)
            # number=round(random()*1234567890)
            id_no='fx'+'-'+ str(number)

            customer=Customer.objects.create(
                user=user,
                first_name=first_name,
                second_name=last_name,
                email=email,
                id_no=id_no
                # password=password,
                # confirm_password=confirm_password,
                # username=username
            )
            Cart.objects.create(customer=customer)
            
          
            form=RegistrationForm()
            return redirect('login')
    template='forex/signup.html'
    context={'form':form}
    return render(request,template,context)


def LoginPage(request):
    if request.method =='POST':
        username=request.POST['username']
        password=request.POST['password']
        
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('landing')
        else:
            messages.info(request,"incorrect Username OR Password")
        
    template='forex/login.html'
    return render(request,template)


def Logout(request):
    logout(request)
    return redirect ('landing')



@login_required(login_url='login')
def Dashboard(request):
    carts=Cart.objects.get(customer=request.user.customer)
    packages=Package.objects.all()
    products=UserPackage.objects.get(customer=request.user.customer)
    # user_inv=Invoice.objects.filter(customer=request.user.customer)
    template='forex/customer.html'
    context={'products':products,} 
    return render(request,template,context)

@authorised_user(roles=['admin'])
def Admin_Panel(request):
    customers=Customer.objects.all()
    context={'customers': customers}
    return render(request, 'forex/admin.html',context)



@login_required(login_url='login')
def Add_to_cart(request,slug):
    product=Package.objects.get(slug=slug)
    
    purchase=False


    if product.category=='basic':
        if request.method=='POST':
            cart=Cart.objects.get(customer=request.user.customer)
            

            if  product in cart.package.all():
                purchase=True

            else:
                # ordered_date=timezone.now()
                # Cart.objects.create(date_ordered=ordered_date)
                cart.package.add(product)
                purchase=True
                

                return HttpResponseRedirect(reverse('basic_package'))
               
     

    if product.category=='pro':
        if request.method=='POST':
            cart=Cart.objects.get(customer=request.user.customer)
            

            if  product in cart.package.all():
                messages.info(request,'you carted this goods')

            else:
                # ordered_date=timezone.now()
                # Cart.objects.create(date_ordered=ordered_date)
                cart.package.add(product)
                purchase=True
                

                return HttpResponseRedirect(reverse('pro_package'))


    if product.category=='premium':
        if request.method=='POST':
            cart=Cart.objects.get(customer=request.user.customer)
            

            if  product in cart.package.all():
                messages.info(request,'you carted this goods')

            else:
                # ordered_date=timezone.now()
                # Cart.objects.create(date_ordered=ordered_date)
                cart.package.add(product)
                purchase=True
                

                return HttpResponseRedirect(reverse('premium_package'))


def Remove_from_cart(request,slug):
    product=Package.objects.get(slug=slug)
   
    if request.method=='GET':
        cart=Cart.objects.get(customer=request.user.customer)
        purchase=True

        if  product in cart.package.all():
            cart.package.remove(product)
            
            

            purchase=False
            

        return HttpResponseRedirect(reverse('cart'))
        # return redirect('detail_package')



def CartFlow(request):
    if request.user.is_authenticated:

        cart=Cart.objects.get(customer=request.user.customer)
        carts=cart.package.all()
        # cart_time=Cart.objects.get(customer=request.user.customer)
        # # print('Package: '+ cart.package)
        cart_total=cart.total_sum()
    else:
        carts= ''
        cart_total=''
    context={'carts': carts,'cart_total':cart_total}
    template='forex/cart.html'
  
    return render(request,template,context)

def exchange_rate(amount):


    url = 'https://www.blockonomics.co/api/price?currency=USD'


frontend/templates/forex/admin.html
{% extends 'base.html' %}
{% load static%}

{% block content%}
 



<div class="container-fluid bg-dark">
  

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid bg-dark" >
            <a class="navbar-brand" href="{%url 'landing' %}">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{%url 'landing' %}">Home</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'profile' %}">Profile</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{%url 'create_package' %}">Create Post</a>
                </li>

                
              </ul>
          
              
                <a href="{%url 'logout' %}"><button class="btn btn-info" type="submit">Logout</button></a>
              
            </div>
          </div>
        </nav>




        <div class="row bg-light">


          <table class="table customer_invoice">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">First Name</th>
                <th scope="col">Second Name</th>
                <th scope="col">Email</th>
                <th scope="col">Id Number</th>
              </tr>
            </thead>
            <tbody>
              {%for customer in customers %}
              <tr>
            
                <th scope="row">{{forloop.counter}}</th>
                <td>{{customer.first_name}}</td>
                <td>{{customer.second_name}}</td>
                <td>{{customer.email}}</td>
                <td>{{customer.id_no}}</td>
                <td><a href="{%url 'user_package' customer.id  %}"><button>Detail</button></a></td>
                <td><a href="{%url 'delete_user' customer.id %}"><button>Remove</button></a></td>
              </tr>
              {%endfor%}
            </tbody>
          </table>

          
        </div>
        
    </div>
    {% endblock %}

frontend/templates/forex/cart.html
{% extends 'base.html'%}


{% load static %}


{% block content%}
{%include 'navbar.html' %}

 <div class="container-fluid  bg-light" style="height: 800px; margin-top: 0;">
{%if bill %}
        <div class="container cart_table" style="position:  relative ; top:90px; background-color: rgb(230, 230, 230);">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">S/N</th>
                        <th scope="col">Package</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Date ordered</th>

                    </tr>
                    </thead>
                            <tbody>
                                {% for cart in carts%}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{cart.name}}</td>
                                <td>{{cart.description| truncatewords:5}}</td>
                                <td>{{cart.price}}</td>
                                <td>{{cart.date_ordered}}</td>
                                
                            </tr>
                            {% endfor %}
                            
                            <tr>
                                <hr style="border: 2px solid black;" >
                                <th scope="row"></th>
                                
                                
                            
                                <tr>
                                    <td colspan="2" align=left><strong>Total:</strong></td>
                                    <td><strong>${{value}}</strong></td>
                                    </tr>
                                    
                                    <tr>
                                    <td colspan="2" align=left><strong>Paid Bitcoins:</strong></td>
                                    <td> <p>Amount: <strong>{{btc}}</strong> BTC ⇌ <strong>{{value}}</strong> USD</p></td>
                                    </tr>
                                
                            </tr>
            
                            <tr>
                            
                                <th scope="row"></th>
                                <td colspan="2" style="font-weight: bolder;">
                                    
                            </tr>
                            
                            </tbody>
                </table>

                <div class="col-md-6 col-sm-12">
                 
                    <p>Bitcoin Address : <strong>{{addr}}</strong></p>
                   
            </div>



        {% else %}
        <div class="container  cart_table" style="position:  relative ; top:90px; background-color: rgb(230, 230, 230);">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">S/N</th>
                    <th scope="col">Package</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">Date ordered</th>

                </tr>
                </thead>
                        <tbody>
                            {% for cart in carts%}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{cart.name}}</td>
                            <td>{{cart.description| truncatewords:5}}</td>
                            <td>{{cart.price}}</td>
                            <td>{{cart.date_ordered}}</td>
                            <td><a href="{%url  'remove_from_cart' cart.slug %}"><button>Undo</button></a></td>
                        </tr>
                        {% endfor %}
                        
                        <tr>
                            <hr style="border: 2px solid black;" >
                            <th scope="row"></th>
                            <td colspan="2" style="font-weight: bolder;">TOTAL</td>
                            <td style="font-weight: bolder;">{{cart_total}}</td>
                            

                            <tr>
                                <td colspan="2" align=left><strong>Total:</strong></td>
                                <td><strong>${{value}}</strong></td>
                                </tr>
                                <tr>
                                <td colspan="2" align=left><strong>Paid Bitcoins:</strong></td>
                                <td><strong>{{paid}}</strong></td>
                                </tr>
                            
                        </tr>
        
                        <tr>
                        
                            <th scope="row"></th>
                            <td colspan="2" style="font-weight: bolder;">
                                
                                <form action="{%url 'checkout' %}" method="POST">{%csrf_token%}
                            
                                <button type="submit" class="btn btn-primary">Proceed</button>
                            </form></td>
                        
                        </tr>
                        
                        </tbody>
            </table>
        </div>  

        {%endif%}
</div>  
{% endblock %}




    

frontend/templates/forex/complete.html
<h1>Complete!!</h1>

frontend/templates/forex/create.html

{% extends 'base.html' %}
{% load static %}



{% block content%}




    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}

        <label for="id_name">Package Name</label>
        {{form.name}} <br>


        <label for="id_price">Price</label>
        {{form.price}}<br>


        <label for="id_price">Category</label>
        {{form.category}}<br>

        <label for="id_image">Package Image</label>
        {{form.image}}<br>


        <label for="id_price">Quantity</label>
        {{form.quantity}}<br>

        <label for="id_description">Description</label>
        {{form.description}}<br>


        <button type="submit">Publish</button>
        
    </form>


{% endblock %}

frontend/templates/forex/customer.html
{% extends 'base.html' %}
{% load static%}

{% block content %}




<div class="container-fluid bg-light dashboard  ">

            
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid bg-dark" >
                  <a class="navbar-brand" href="{%url 'landing' %}"> X-Tradr</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'landing' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{%url 'profile' %}">Profile</a>
                      </li>
            
                    
                      
                    </ul>
                    <a href="{%url 'logout' %}"><button class="btn btn-info" type="submit">Logout</button></a>
                  </div>
                </div>
              </nav>
          

  






      
      <div class="row  packages_holder " style="position: relative;top: 20px;"  >

        
      
        {% for product in products.package.all%}

        
         

            <div class="  col-lg-3 col-md-4 col-8 offset-lg-1 offset-3 offset-md-2 bg-secondary    packages" style="border: 1px solid red; position: relative; right: 50px;" >
                <h1 style="text-align: center; position: relative; top: 20%;" class="text-light" >{{product.name}}</h2>
            </div>
           
      
        
        {%endfor%}

     

      </div>

      <!-- <br><br>
      <table class="table customer_invoice">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Invoice-Id</th>
            <th scope="col">Order Id</th>
            <th scope="col">Amt paid(in btc)</th>
            <th scope="col">Amt paid(in usd)</th>
          </tr>
        </thead>
        <tbody>
          {%for inv in user_inv %}
          <tr>
        
            <th scope="row">{{forloop.counter}}</th>
            <td>{{inv.id}}</td>
            <td>{{inv.order_id}}</td>
            <td>{{inv.btc_value|floatformat:5}}</td>
            <td>{{inv.usd_value}}</td>
           
          </tr>
          {%endfor%}
        </tbody>
      </table>
     -->

     

 
</div>
    {% endblock %}

frontend/templates/forex/detail.html
{% extends 'base.html' %}

{% load static %}


{% block content%}
{%include 'navbar.html' %}

<div class="container-fluid  bg-light" style="height: 800px; margin-top: 0;">
    <br><br><br><br>



<div class="row">

    <div class="col" style="border: 1px solid black;">

        <h1>Hello</h1>
    </div>


    
    
    <div class="col"style="border: 1px solid black;">
        <div class="col">
            <h1>{{package.name}}</h1>
        </div>
            <em>${{package.product_price}}</em>
            <p>{{package.description}}</p>
        </div>



</div>
        
        

<!-- 
                 {% if purchase %}

                    <a href="{%url  'cart' %}"><button>Go To Cart</button></a>

                    {% else %} 



                    <form action="{%url  'Add_to_cart' package.slug %}" method="POST" >
                        {%csrf_token%}
                    
                        <button type="submit" name="package_id" value="{{package.slug}}" >Buy</button>
                    </form>


                {% endif %}
 -->



                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
<!-- 
<h1>{{request.user}}</h1>

    {% if user.is_staff %}
    <a href="{%url 'update_package' package.slug %}"><button>Edit</button></a>
    <a href="{%url 'delete_package' package.slug %}"><button>Delete</button></a>

    {% endif %} -->

</div>
{% endblock %}

frontend/templates/forex/invoice.html
{% extends 'base.html' %}

{% load static %}


{% block content%}
{%include 'navbar.html' %}


<h1>{{request.user}}</h1>


    
        
                        
            
  
{% endblock %}



frontend/templates/forex/package_create.html
{%extends 'base.html' %}


{% load static %}



{% block content%}

<form action="" method="POST">
    {%csrf_token%}

    {{form.as_p}}
    <button type="submit">Send</button>
</form>

{%endblock%}

frontend/templates/forex/success.html
<h1>SUCCESS!!</h1>

frontend/templates/forex/update.html

{% extends 'base.html' %}
{% load static %}



{% block content%}
{%include 'navbar.html' %}

    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}

        <label for="id_name">Package Name</label>
        {{form.name}} <br>


        <label for="id_price">Price</label>
        {{form.price}}<br>



        <label for="id_image">Package Image</label>
        {{form.image}}<br>



        <label for="id_description">Description</label>
        {{form.description}}<br>


        <button type="submit">Publish</button>
        
    </form>

{% endblock %}